[package]
name = "kawaii-kinetics"
version = "0.1.0"
edition = "2021"

[dependencies]
aniscraper = { version = "0.1.2" }
moka = { version = "0.12.8", features = ["future"] }
serde = "1.0.210"
serde_json = "1.0.128"
thiserror = "1.0.63"
tokio = { version = "1.43.0", features = ["full"] }
axum = "0.8.1"
shuttle-axum = "0.51.0"
shuttle-runtime = "0.51.0"
